# -*- coding: utf-8 -*-
"""Untitled57.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-iYJOsQ7KFWE_fAvFkxkNpWtr0jb55Ia
"""

!pip install -q kagglehub
import kagglehub
import os
import matplotlib.pyplot as plt
from PIL import Image

path = kagglehub.dataset_download("dimaspashaakrilian/openearthmap")
base = os.path.join(path, "OpenEarthMap_wo_xBD")


pairs = []
for city in os.listdir(base):
    img_dir = os.path.join(base, city, "images")
    lbl_dir = os.path.join(base, city, "labels")
    if os.path.isdir(img_dir) and os.path.isdir(lbl_dir):
        imgs = [f for f in os.listdir(img_dir) if f.endswith(('.png','.jpg','.tif'))]
        lbls = [f for f in os.listdir(lbl_dir) if f.endswith(('.png','.tif'))]
        count = 0
        for img in imgs:
            if count >= 4:
                break
            base_name = os.path.splitext(img)[0]
            match = next((l for l in lbls if base_name in l), None)
            if match:
                pairs.append((os.path.join(img_dir, img), os.path.join(lbl_dir, match)))
                count += 1

print(f"✅ Собрано пар: {len(pairs)}")

# Вывод 10 пар
fig, ax = plt.subplots(10, 2, figsize=(12, 35))
for i in range(10):
    img, msk = pairs[i]
    ax[i,0].imshow(Image.open(img))
    ax[i,0].set_title(f"Оригинал: {os.path.basename(img)}", fontsize=10)
    ax[i,0].axis('off')
    ax[i,1].imshow(Image.open(msk))
    ax[i,1].set_title(f"Маска: {os.path.basename(msk)}", fontsize=10)
    ax[i,1].axis('off')
plt.tight_layout()
plt.show()

import torch
from transformers import AutoImageProcessor, Mask2FormerForUniversalSegmentation
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
import os
import random
from pathlib import Path

print("="*60)
print("ТЕСТИРОВАНИЕ МОДЕЛИ mask2former_finetuned_new")
print("="*60)

# 1. ПУТЬ К МОДЕЛИ (ЭТО ПАПКА, НЕ ZIP)
model_path = "/content/mask2former_finetuned_new"

# Если нет папки, ищем любую папку с моделью
if not os.path.exists(model_path):
    print("🔍 Ищем модель...")
    for item in os.listdir("/content"):
        item_path = os.path.join("/content", item)
        if os.path.isdir(item_path):
            # Проверяем наличие файлов модели
            if os.path.exists(os.path.join(item_path, "config.json")):
                model_path = item_path
                print(f"✅ Найдена модель в: {model_path}")
                break

if not os.path.exists(model_path):
    print("❌ Модель не найдена!")
    print("Содержимое /content:", os.listdir("/content"))
    exit()

# 2. ЗАГРУЖАЕМ МОДЕЛЬ
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"\n🔧 Устройство: {device}")
print(f"📂 Загрузка модели из {model_path}...")

try:
    processor = AutoImageProcessor.from_pretrained(model_path, local_files_only=True)
    model = Mask2FormerForUniversalSegmentation.from_pretrained(model_path, local_files_only=True)
    model.to(device)
    model.eval()
    print("✅ Модель загружена успешно!")
    print(f"📊 Классов в модели: {model.config.num_labels}")
except Exception as e:
    print(f"❌ Ошибка загрузки: {e}")
    exit()

# 3. ЗДЕСЬ ДОЛЖНЫ БЫТЬ ВАШИ ПАРЫ (img_path, mask_path)
# Пример: pairs = [(путь_к_изображению, путь_к_маске), ...]
# ВАМ НУЖНО ЗАГРУЗИТЬ ВАШИ ТЕСТОВЫЕ ДАННЫЕ

print("\n⚠️ ВНИМАНИЕ: Нужно загрузить тестовые данные!")
print("Переменная 'pairs' не определена в вашем коде")
print("Вам нужно загрузить dataset.zip и создать список пар")

# Если у вас есть dataset.zip, добавьте сюда код его распаковки
# и создания списка pairs

# Пример загрузки данных (раскомментируйте и адаптируйте):
"""
# Распаковка тестовых данных
if os.path.exists("/content/dataset.zip"):
    import zipfile
    with zipfile.ZipFile("/content/dataset.zip", 'r') as zip_ref:
        zip_ref.extractall("/content/test_data")

    # Создание списка пар
    test_path = Path("/content/test_data")
    pairs = []
    # ... ваш код создания пар
"""

# 4. ЦВЕТА ДЛЯ ВИЗУАЛИЗАЦИИ
colors = np.array([
    [0, 0, 0],       # 0: фон
    [0, 255, 0],     # 1: растительность
    [255, 255, 0],   # 2: земля
    [0, 0, 255],     # 3: вода
    [255, 0, 0],     # 4: здания
    [128, 128, 128], # 5: дороги
    [255, 0, 255],   # 6: другое
    [255, 165, 0],   # 7: дополнительный
])

def mask_to_rgb(mask_np, color_map):
    h, w = mask_np.shape
    rgb_mask = np.zeros((h, w, 3), dtype=np.uint8)
    for class_id, color in enumerate(color_map):
        if class_id < len(color_map):
            rgb_mask[mask_np == class_id] = color
    return rgb_mask

# 5. ЕСЛИ У ВАС ЕСТЬ pairs, ТО ТЕСТИРУЕМ
if 'pairs' in locals() and len(pairs) > 0:
    test_pairs = random.sample(pairs, min(10, len(pairs)))

    print(f"\n📊 Тестируем на {len(test_pairs)} изображениях")

    # Визуализация
    fig, axes = plt.subplots(len(test_pairs), 3, figsize=(15, 4*len(test_pairs)))

    for idx, (img_path, mask_path) in enumerate(test_pairs):
        # Загружаем изображение
        image = Image.open(img_path).convert("RGB")
        original_size = image.size[::-1]

        # Предсказание
        inputs = processor(images=image, return_tensors="pt")
        inputs = {k: v.to(device) for k, v in inputs.items()}

        with torch.no_grad():
            outputs = model(**inputs)

        # Получаем маску
        pred_mask = processor.post_process_semantic_segmentation(outputs, target_sizes=[original_size])[0]
        pred_mask_np = pred_mask.cpu().numpy()
        pred_rgb = mask_to_rgb(pred_mask_np, colors)

        # Загружаем настоящую маску
        true_mask = Image.open(mask_path)
        if true_mask.mode != 'L':
            true_mask = true_mask.convert('L')
        true_mask = true_mask.resize(original_size[::-1], Image.NEAREST)
        true_mask_np = np.array(true_mask, dtype=np.int64)
        true_rgb = mask_to_rgb(true_mask_np, colors)

        # Отображаем
        if len(test_pairs) == 1:
            axes[0].imshow(image)
            axes[0].set_title(f"Оригинал", fontsize=10)
            axes[0].axis('off')

            axes[1].imshow(pred_rgb)
            axes[1].set_title(f"Предсказание", fontsize=10)
            axes[1].axis('off')

            axes[2].imshow(true_rgb)
            axes[2].set_title(f"Ground Truth", fontsize=10)
            axes[2].axis('off')
        else:
            axes[idx, 0].imshow(image)
            axes[idx, 0].set_title(f"Оригинал {idx+1}", fontsize=10)
            axes[idx, 0].axis('off')

            axes[idx, 1].imshow(pred_rgb)
            axes[idx, 1].set_title(f"Предсказание {idx+1}", fontsize=10)
            axes[idx, 1].axis('off')

            axes[idx, 2].imshow(true_rgb)
            axes[idx, 2].set_title(f"Ground Truth {idx+1}", fontsize=10)
            axes[idx, 2].axis('off')

    plt.tight_layout()
    plt.show()

    # Метрики
    print("\n" + "="*60)
    print("РАСЧЕТ МЕТРИК")
    print("="*60)

    from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

    all_pred = []
    all_true = []

    for img_path, mask_path in test_pairs:
        image = Image.open(img_path).convert("RGB")
        original_size = image.size[::-1]

        inputs = processor(images=image, return_tensors="pt")
        inputs = {k: v.to(device) for k, v in inputs.items()}

        with torch.no_grad():
            outputs = model(**inputs)

        pred_mask = processor.post_process_semantic_segmentation(outputs, target_sizes=[original_size])[0]
        pred_mask_np = pred_mask.cpu().numpy().flatten()

        true_mask = Image.open(mask_path)
        if true_mask.mode != 'L':
            true_mask = true_mask.convert('L')
        true_mask = true_mask.resize(original_size[::-1], Image.NEAREST)
        true_mask_np = np.array(true_mask, dtype=np.int64).flatten()

        all_pred.extend(pred_mask_np)
        all_true.extend(true_mask_np)

    accuracy = accuracy_score(all_true, all_pred)
    precision = precision_score(all_true, all_pred, average='weighted', zero_division=0)
    recall = recall_score(all_true, all_pred, average='weighted', zero_division=0)
    f1 = f1_score(all_true, all_pred, average='weighted', zero_division=0)

    print(f"\n📊 Метрики на {len(test_pairs)} тестовых изображениях:")
    print(f"   Accuracy:  {accuracy:.4f}")
    print(f"   Precision: {precision:.4f}")
    print(f"   Recall:    {recall:.4f}")
    print(f"   F1-Score:  {f1:.4f}")
else:
    print("\n❌ Нет данных для тестирования!")
    print("Загрузите dataset.zip и создайте список 'pairs'")

print("\n✅ Тестирование завершено!")

import torch
from transformers import AutoImageProcessor, Mask2FormerForUniversalSegmentation
from PIL import Image
import numpy as np
import os
import zipfile
import shutil
from tqdm import tqdm
import time
from pathlib import Path
from google.colab import files

print("="*60)
print("СЕГМЕНТАЦИЯ ИЗОБРАЖЕНИЙ ИЗ arcgis.zip")
print("="*60)

# 1. ПУТЬ К ZIP ФАЙЛУ С ДАННЫМИ
zip_path = "/content/arcgis.zip"

# Проверяем существует ли zip
if not os.path.exists(zip_path):
    for file in os.listdir("/content"):
        if file.endswith(".zip") and "arcgis" in file:
            zip_path = os.path.join("/content", file)
            print(f"✅ Найден zip: {zip_path}")
            break

if not os.path.exists(zip_path):
    print("❌ Файл arcgis.zip не найден в /content!")
    print("Содержимое /content:", os.listdir("/content"))
    exit()

print(f"\n📦 Распаковка {zip_path}...")

# 2. РАСПАКОВЫВАЕМ ДАННЫЕ
extract_path = "/content/arcgis_extracted"
os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)
print(f"✅ Распаковано в {extract_path}")

# 3. НАХОДИМ ПУТЬ К МОДЕЛИ (ПРОСТО ПАПКА, НЕ ZIP)
model_folder = None

# Смотрим все папки в /content
print("\n🔍 Поиск папки с моделью...")
for item in os.listdir("/content"):
    item_path = os.path.join("/content", item)

    # Проверяем, что это папка
    if os.path.isdir(item_path):
        # Ищем config.json
        config_path = os.path.join(item_path, "config.json")
        if os.path.exists(config_path):
            # Проверяем наличие весов модели
            has_weights = (os.path.exists(os.path.join(item_path, "pytorch_model.bin")) or
                          os.path.exists(os.path.join(item_path, "model.safetensors")))

            if has_weights:
                model_folder = item_path
                print(f"✅ Найдена модель в папке: {model_folder}")
                break
            else:
                print(f"⚠️ В папке {item} есть config.json, но нет файлов весов")

# Если не нашли, ищем в распакованных данных (на всякий случай)
if model_folder is None:
    print("\n🔍 Ищем модель в распакованных данных...")
    for root, dirs, files_list in os.walk(extract_path):
        if "config.json" in files_list:
            if "pytorch_model.bin" in files_list or "model.safetensors" in files_list:
                model_folder = root
                print(f"✅ Модель найдена в: {model_folder}")
                break

if model_folder is None:
    print("\n❌ МОДЕЛЬ НЕ НАЙДЕНА!")
    print("\nСодержимое /content:")
    for item in os.listdir("/content"):
        item_path = os.path.join("/content", item)
        if os.path.isdir(item_path):
            print(f"  📁 {item}/")
            try:
                files_list = os.listdir(item_path)
                for subitem in files_list[:5]:
                    print(f"     - {subitem}")
                if len(files_list) > 5:
                    print(f"     ... и еще {len(files_list)-5} файлов")
            except:
                pass
        else:
            print(f"  📄 {item}")

    print("\n💡 Подсказка: Папка с моделью должна содержать файлы:")
    print("   - config.json")
    print("   - pytorch_model.bin ИЛИ model.safetensors")
    exit()

# 4. ЗАГРУЖАЕМ МОДЕЛЬ
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"\n🔧 Устройство: {device}")
print(f"📂 Загрузка модели из: {model_folder}")

try:
    processor = AutoImageProcessor.from_pretrained(model_folder, local_files_only=True)
    model = Mask2FormerForUniversalSegmentation.from_pretrained(model_folder, local_files_only=True)
    model.to(device)
    model.eval()
    print("✅ МОДЕЛЬ УСПЕШНО ЗАГРУЖЕНА!")
    print(f"📊 Количество классов: {model.config.num_labels}")

    if hasattr(model.config, 'id2label'):
        print("\n🏷️ Классы модели:")
        for idx, label in list(model.config.id2label.items())[:8]:
            print(f"   {idx}: {label}")

except Exception as e:
    print(f"❌ Ошибка загрузки модели: {e}")
    exit()

# 5. ФУНКЦИЯ ДЛЯ СЕГМЕНТАЦИИ
def segment_image(image_path):
    """Сегментирует одно изображение и возвращает RGB маску"""
    image = Image.open(image_path).convert("RGB")
    original_size = image.size[::-1]

    inputs = processor(images=image, return_tensors="pt")
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)

    pred_mask = processor.post_process_semantic_segmentation(outputs, target_sizes=[original_size])[0]
    pred_mask_np = pred_mask.cpu().numpy()

    # Цветовая схема для маски
    colors = np.array([
        [0, 0, 0],       # 0: фон
        [0, 255, 0],     # 1: растительность
        [255, 255, 0],   # 2: земля
        [0, 0, 255],     # 3: вода
        [255, 0, 0],     # 4: здания
        [128, 128, 128], # 5: дороги
        [255, 0, 255],   # 6: другое
        [255, 165, 0],   # 7: дополнительный
    ])

    h, w = pred_mask_np.shape
    rgb_mask = np.zeros((h, w, 3), dtype=np.uint8)
    for class_id, color in enumerate(colors):
        if class_id < len(colors):
            rgb_mask[pred_mask_np == class_id] = color

    return rgb_mask

# 6. НАХОДИМ НУЖНЫЕ ПАПКИ
base_path = Path(extract_path)

# Ищем структуру: arcgis/arcgis/18/
arcgis_18_path = None
for path in base_path.rglob("18"):
    if path.is_dir():
        arcgis_18_path = path
        break

if arcgis_18_path is None:
    print("❌ Папка '18' не найдена!")
    print("\nСтруктура распакованных файлов:")
    for root, dirs, files_list in os.walk(extract_path):
        level = root.replace(extract_path, '').count(os.sep)
        if level <= 3:
            indent = ' ' * 2 * level
            print(f"{indent}{os.path.basename(root)}/")
        if level >= 3:
            break
    exit()

print(f"\n📁 Найдена папка 18: {arcgis_18_path}")

# Получаем все числовые папки внутри 18
numeric_folders = [f for f in arcgis_18_path.iterdir() if f.is_dir() and f.name.isdigit()]

print(f"📁 Найдено числовых папок: {len(numeric_folders)}")
print(f"   Примеры: {[f.name for f in numeric_folders[:5]]}")

# 7. ОПРЕДЕЛЯЕМ ДИАПАЗОНЫ ДЛЯ СЕГМЕНТАЦИИ
folder_range = range(145028, 145081)  # папки 145028-145080
file_range = range(78407, 78452)      # файлы 78407-78451

print(f"\n🎯 Целевые диапазоны:")
print(f"   Папки: {folder_range.start} - {folder_range.stop-1}")
print(f"   Файлы: {file_range.start} - {file_range.stop-1}")

# 8. СЕГМЕНТАЦИЯ ПО ПАПКАМ (ВСЕ СОХРАНЯЕМ В ОДНУ ПАПКУ)
output_base = "/content/all_segmented_results"
os.makedirs(output_base, exist_ok=True)

# Создаем список папок для обработки
target_folders = []
for folder_num in folder_range:
    folder_path = arcgis_18_path / str(folder_num)
    if folder_path.exists() and folder_path.is_dir():
        target_folders.append(folder_path)

print(f"\n📊 Найдено целевых папок: {len(target_folders)} из {len(folder_range)}")

if len(target_folders) == 0:
    print("\n❌ Нет целевых папок! Проверьте диапазон.")
    exit()

# Статистика по всем папкам
total_images = 0
total_time_start = time.time()

# Обрабатываем каждую папку
for folder_idx, folder_path in enumerate(target_folders, 1):
    folder_name = folder_path.name
    print(f"\n{'='*60}")
    print(f"📁 Обработка папки {folder_idx}/{len(target_folders)}: {folder_name}")
    print(f"{'='*60}")

    # Находим все файлы в диапазоне
    image_files = []
    for file_num in file_range:
        for ext in ['.jpg', '.jpeg', '.png', '.tif', '.tiff']:
            file_path = folder_path / f"{file_num}{ext}"
            if file_path.exists():
                image_files.append(file_path)
                break

    print(f"📷 Найдено изображений: {len(image_files)}")

    if len(image_files) == 0:
        print(f"⚠️ В папке {folder_name} нет изображений в указанном диапазоне!")
        continue

    total_images += len(image_files)

    # Создаем папку для результатов этой папки
    output_folder = os.path.join(output_base, f"{folder_name}_segment")
    os.makedirs(output_folder, exist_ok=True)

    # Сегментируем
    times = []
    with tqdm(total=len(image_files), desc=f"Сегментация {folder_name}", unit="изобр") as pbar:
        for img_idx, img_path in enumerate(image_files, 1):
            start_time = time.time()

            segmented_mask = segment_image(img_path)

            output_path = os.path.join(output_folder, f"{img_path.stem}_segmented.png")
            Image.fromarray(segmented_mask).save(output_path)

            elapsed = time.time() - start_time
            times.append(elapsed)

            avg_time = np.mean(times)
            remaining = avg_time * (len(image_files) - img_idx)

            pbar.set_postfix({
                'время': f'{elapsed:.2f}с',
                'сред': f'{avg_time:.2f}с',
                'осталось': f'{remaining:.1f}с'
            })
            pbar.update(1)

    print(f"✅ Папка {folder_name} завершена!")
    print(f"   Среднее время: {np.mean(times):.2f} сек")

# Общая статистика
total_time = time.time() - total_time_start
print(f"\n{'='*60}")
print("📊 ОБЩАЯ СТАТИСТИКА:")
print(f"{'='*60}")
print(f"✅ Обработано папок: {len(target_folders)}")
print(f"✅ Всего изображений: {total_images}")
print(f"⏱️ Общее время: {total_time/60:.2f} минут")
print(f"⚡ Среднее время на изображение: {total_time/total_images:.2f} сек")

# 9. СОЗДАЕМ ОБЩИЙ ZIP АРХИВ СО ВСЕМИ РЕЗУЛЬТАТАМИ
print(f"\n📦 Создание общего ZIP архива...")
zip_filename = "all_segmented_results.zip"
zip_path_final = os.path.join("/content", zip_filename)

with zipfile.ZipFile(zip_path_final, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files_list in os.walk(output_base):
        for file in files_list:
            file_path = os.path.join(root, file)
            # Сохраняем структуру папок в архиве
            arcname = os.path.relpath(file_path, output_base)
            zipf.write(file_path, arcname)

file_size = os.path.getsize(zip_path_final) / (1024*1024)
print(f"✅ Архив создан: {zip_filename}")
print(f"📦 Размер: {file_size:.2f} MB")

# 10. СКАЧИВАЕМ ВСЕ ОДНИМ ФАЙЛОМ
print(f"\n📥 Скачивание {zip_filename} на ваш компьютер...")
files.download(zip_path_final)

print(f"\n{'='*60}")
print("✅ ВСЕ ЗАВЕРШЕНО!")
print(f"{'='*60}")
print(f"\n🎉 Результаты сегментации скачаны в файле: {zip_filename}")

from PIL import Image
from pathlib import Path
import os

def merge_tiles(base_dir, n, m):
    """
    Объединяет тайлы в мозаику n x m

    base_dir: /content/all_segmented_results
    n: количество тайлов по горизонтали (X)
    m: количество тайлов по вертикали (Y)
    """
    # Получаем все X папки и сортируем
    x_folders = sorted([f for f in Path(base_dir).glob("*_segment")],
                       key=lambda x: int(x.name.replace("_segment", "")))

    # Берем первые n папок по X
    x_folders = x_folders[:n]

    # Получаем все Y файлы из первой папки и сортируем (по убыванию, т.к. Y растет вверх)
    first_folder = x_folders[0]
    y_files = sorted([f for f in first_folder.glob("*_segmented.png")],
                     key=lambda y: int(y.stem.replace("_segmented", "")),
                     reverse=True)

    # Берем первые m файлов по Y
    y_files = y_files[:m]

    # Загружаем размер тайла
    sample = Image.open(y_files[0])
    w, h = sample.size

    # Создаем мозаику
    mosaic = Image.new('RGB', (w * n, h * m))

    # Заполняем
    for i, x_folder in enumerate(x_folders):
        x = x_folder.name.replace("_segment", "")
        for j, y_file in enumerate(y_files):
            y = y_file.stem.replace("_segmented", "")
            tile_path = x_folder / f"{y}_segmented.png"
            tile = Image.open(tile_path)
            mosaic.paste(tile, (i * w, j * h))

    # Координаты левого нижнего угла (первая X папка, последний Y файл)
    bottom_left_x = x_folders[0].name.replace("_segment", "")
    bottom_left_y = y_files[-1].stem.replace("_segmented", "")

    # Сохраняем
    output_dir = f"/content/merged_{bottom_left_x}"
    os.makedirs(output_dir, exist_ok=True)
    output_path = f"{output_dir}/{bottom_left_y}.png"
    mosaic.save(output_path)

    print(f"✅ Сохранено: {output_path}")
    print(f"   Размер: {n} x {m} тайлов")

# Пример: объединить 10x10 тайлов
merge_tiles("/content/all_segmented_results", 10, 10)

from PIL import Image
from pathlib import Path
import os

def merge_all_tiles(base_dir, n, m):
    """
    Проходит по всему прямоугольнику с шагом 1 и создает мозаики n x m

    base_dir: /content/all_segmented_results
    n: количество тайлов по горизонтали (X)
    m: количество тайлов по вертикали (Y)
    """
    # Получаем все X папки и сортируем
    all_x = sorted([int(f.name.replace("_segment", "")) for f in Path(base_dir).glob("*_segment")])

    # Получаем все Y файлы из первой папки
    first_folder = Path(base_dir) / f"{all_x[0]}_segment"
    all_y = sorted([int(f.stem.replace("_segmented", "")) for f in first_folder.glob("*_segmented.png")], reverse=True)

    # Загружаем размер тайла
    sample = Image.open(Path(base_dir) / f"{all_x[0]}_segment" / f"{all_y[0]}_segmented.png")
    w, h = sample.size

    # Проходим по всем возможным позициям левого нижнего угла
    for idx_x, start_x in enumerate(all_x[:-n+1]):
        for idx_y, start_y in enumerate(all_y[:-m+1]):
            # Берем n папок по X начиная с start_x
            x_folders = [f"{x}_segment" for x in all_x[idx_x:idx_x+n]]

            # Берем m файлов по Y начиная с start_y
            y_values = all_y[idx_y:idx_y+m]

            # Создаем мозаику
            mosaic = Image.new('RGB', (w * n, h * m))

            for i, x_folder in enumerate(x_folders):
                for j, y in enumerate(y_values):
                    tile_path = Path(base_dir) / x_folder / f"{y}_segmented.png"
                    tile = Image.open(tile_path)
                    mosaic.paste(tile, (i * w, j * h))

            # Координаты левого нижнего угла
            bottom_left_x = all_x[idx_x]
            bottom_left_y = y_values[-1]

            # Сохраняем
            output_dir = f"/content/merged_{bottom_left_x}"
            os.makedirs(output_dir, exist_ok=True)
            output_path = f"{output_dir}/{bottom_left_y}.png"
            mosaic.save(output_path)

            print(f"✅ {bottom_left_x}_{bottom_left_y} ({idx_x+1}/{len(all_x)-n+1}, {idx_y+1}/{len(all_y)-m+1})")

merge_all_tiles("/content/all_segmented_results", 10, 10)            ##здесь задается путь к файлу и параметры n m

import os
import zipfile
from PIL import Image
import torch
import numpy as np
from pathlib import Path
from transformers import AutoImageProcessor, Mask2FormerForUniversalSegmentation

# Распаковываем модель из zip
zip_path = "/content/mask2former_finetuned_new.zip"
extract_path = "/content/mask2former_finetuned_new"

if os.path.exists(zip_path):
    print("📦 Распаковка модели...")
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print("✅ Модель распакована")
else:
    print("❌ mask2former_finetuned_new.zip не найден!")
    exit()

# Поиск папки с моделью
model_path = None
for root, dirs, files in os.walk(extract_path):
    if "config.json" in files:
        has_weights = ("pytorch_model.bin" in files or "model.safetensors" in files)
        if has_weights:
            model_path = root
            break

if model_path is None:
    print("❌ Модель не найдена!")
    exit()

print(f"✅ Модель найдена: {model_path}")

# Загружаем модель
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
processor = AutoImageProcessor.from_pretrained(model_path, local_files_only=True)
model = Mask2FormerForUniversalSegmentation.from_pretrained(model_path, local_files_only=True)
model.to(device)
model.eval()

# Поиск папки 18
arcgis_18 = None
for path in Path("/content").rglob("18"):
    if path.is_dir():
        arcgis_18 = path
        break

if arcgis_18 is None:
    print("❌ Папка '18' не найдена!")
    exit()

print(f"✅ Данные найдены: {arcgis_18}")

# Параметры сетки - квадрат 8x8
N, M = 8, 8

# Получаем все X папки и сортируем
all_x = sorted([int(f.name) for f in arcgis_18.iterdir() if f.is_dir() and f.name.isdigit()])

# Находим непрерывную последовательность X (шаг 1)
continuous_x = []
for i in range(len(all_x) - 1):
    if not continuous_x:
        continuous_x.append(all_x[i])
    if all_x[i+1] == all_x[i] + 1:
        continuous_x.append(all_x[i+1])
    else:
        break

x_values = continuous_x[:N]
print(f"X папки (непрерывные): {x_values}")

# Получаем все Y файлы из первой папки и сортируем (по убыванию)
first_folder = arcgis_18 / str(x_values[0])
all_y = sorted([int(f.stem) for f in first_folder.glob("*") if f.suffix in ['.jpg', '.png', '.jpeg']], reverse=True)

# Находим непрерывную последовательность Y (шаг 1)
continuous_y = []
for i in range(len(all_y) - 1):
    if not continuous_y:
        continuous_y.append(all_y[i])
    if all_y[i+1] == all_y[i] - 1:  # по убыванию
        continuous_y.append(all_y[i+1])
    else:
        break

y_values = continuous_y[:M]
print(f"Y значения (непрерывные): {y_values}")

# Собираем тайлы
tiles = []
for x in x_values:
    x_folder = arcgis_18 / str(x)
    for y in y_values:
        img_path = x_folder / f"{y}.jpg"
        if not img_path.exists():
            img_path = x_folder / f"{y}.png"
        if img_path.exists():
            tiles.append((x, y, img_path))

print(f"Найдено тайлов: {len(tiles)} (ожидалось {N*M})")

if len(tiles) == 0:
    print("❌ Тайлы не найдены!")
    exit()

# Загружаем первый тайл для размера
sample = Image.open(tiles[0][2])
w, h = sample.size

# Объединяем в мозаику
big_image = Image.new('RGB', (w * N, h * M))
for x, y, path in tiles:
    i = x_values.index(x)
    j = y_values.index(y)
    img = Image.open(path)
    big_image.paste(img, (i * w, j * h))

big_image.save("big_mosaic_8x8.png")
print(f"Мозаика {N}x{M} создана, сегментируем...")

# Сегментация
inputs = processor(images=big_image, return_tensors="pt")
inputs = {k: v.to(device) for k, v in inputs.items()}
with torch.no_grad():
    outputs = model(**inputs)

pred_mask = processor.post_process_semantic_segmentation(outputs, target_sizes=[big_image.size[::-1]])[0]
pred_mask_np = pred_mask.cpu().numpy()

# Цветная маска
colors = np.array([[0,0,0], [0,255,0], [255,255,0], [0,0,255], [255,0,0], [128,128,128], [255,0,255], [255,165,0]])
h, w = pred_mask_np.shape
rgb_mask = np.zeros((h, w, 3), dtype=np.uint8)
for i, color in enumerate(colors):
    if i < len(colors):
        rgb_mask[pred_mask_np == i] = color

result = Image.fromarray(rgb_mask)
result.save("segmented_mosaic_8x8.png")
print("✅ Готово! Результат: segmented_mosaic_8x8.png")

from PIL import Image
from pathlib import Path
import os

def merge_original_tiles(base_path, n, m):
    """
    Объединяет原始 тайлы в мозаики n x m с шагом 1

    base_path: путь к папке 18 (например /content/arcgis_extracted/arcgis/arcgis/18)
    n: количество тайлов по горизонтали (X)
    m: количество тайлов по вертикали (Y)
    """
    # Получаем все X папки и сортируем
    all_x = sorted([int(f.name) for f in Path(base_path).iterdir() if f.is_dir() and f.name.isdigit()])

    # Получаем все Y файлы из первой папки
    first_folder = Path(base_path) / str(all_x[0])
    all_y = sorted([int(f.stem) for f in first_folder.glob("*") if f.suffix in ['.jpg', '.png', '.jpeg']], reverse=True)

    # Загружаем размер тайла
    sample = Image.open(first_folder / f"{all_y[0]}.jpg")
    w, h = sample.size

    # Проходим по всем возможным позициям левого нижнего угла
    for idx_x, start_x in enumerate(all_x[:-n+1]):
        for idx_y, start_y in enumerate(all_y[:-m+1]):
            # Берем n папок по X начиная с start_x
            x_folders = all_x[idx_x:idx_x+n]

            # Берем m файлов по Y начиная с start_y
            y_values = all_y[idx_y:idx_y+m]

            # Создаем мозаику
            mosaic = Image.new('RGB', (w * n, h * m))

            for i, x in enumerate(x_folders):
                x_folder = Path(base_path) / str(x)
                for j, y in enumerate(y_values):
                    tile_path = x_folder / f"{y}.jpg"
                    if not tile_path.exists():
                        tile_path = x_folder / f"{y}.png"
                    tile = Image.open(tile_path)
                    mosaic.paste(tile, (i * w, j * h))

            # Координаты левого нижнего угла
            bottom_left_x = all_x[idx_x]
            bottom_left_y = y_values[-1]

            # Сохраняем
            output_dir = f"/content/original_merged_{bottom_left_x}"
            os.makedirs(output_dir, exist_ok=True)
            output_path = f"{output_dir}/{bottom_left_y}.png"
            mosaic.save(output_path)

            print(f"✅ {bottom_left_x}_{bottom_left_y} ({idx_x+1}/{len(all_x)-n+1}, {idx_y+1}/{len(all_y)-m+1})")

# Использование:
# merge_original_tiles("/content/arcgis_extracted/arcgis/arcgis/18", 8, 8)

from PIL import Image
from pathlib import Path
import os
import zipfile

# Путь к данным arcgis
arcgis_path = "/content/arcgis_extracted/arcgis/arcgis/18"

# Проверяем существование
if not os.path.exists(arcgis_path):
    print("🔍 Ищем папку 18...")
    for path in Path("/content").rglob("18"):
        if path.is_dir():
            arcgis_path = str(path)
            break

print(f"📁 Данные: {arcgis_path}")

# Диапазоны
x_range_full = list(range(145028, 145081))  # 145028-145080
y_range_full = list(range(78451, 78406, -1))  # 78451-78407

print(f"Всего X: {len(x_range_full)}, Y: {len(y_range_full)}")

# Создаем папку для результатов
output_root = "/content/arcgis_merged_2x2_step2"
os.makedirs(output_root, exist_ok=True)

# Размер тайла
first_folder = Path(arcgis_path) / str(x_range_full[0])
sample = Image.open(first_folder / f"{y_range_full[0]}.jpg")
w, h = sample.size
print(f"Размер тайла: {w}x{h}")

# Объединяем с шагом 2
count = 0
for i in range(0, len(x_range_full) - 1, 2):
    x1 = x_range_full[i]
    x2 = x_range_full[i + 1]

    for j in range(0, len(y_range_full) - 1, 2):
        y1 = y_range_full[j]      # верхний ряд
        y2 = y_range_full[j + 1]  # нижний ряд

        # Создаем мозаику 2x2
        mosaic = Image.new('RGB', (w * 2, h * 2))

        # Расположение тайлов
        # (x1, y1) - левый верхний
        # (x2, y1) - правый верхний
        # (x1, y2) - левый нижний
        # (x2, y2) - правый нижний
        tiles = [
            (x1, y1, 0, 0),
            (x2, y1, w, 0),
            (x1, y2, 0, h),
            (x2, y2, w, h)
        ]

        for tx, ty, px, py in tiles:
            tile_path = Path(arcgis_path) / str(tx) / f"{ty}.jpg"
            if not tile_path.exists():
                tile_path = Path(arcgis_path) / str(tx) / f"{ty}.png"
            if tile_path.exists():
                tile = Image.open(tile_path)
                mosaic.paste(tile, (px, py))

        # Координаты левого нижнего угла (x1, y2)
        output_path = os.path.join(output_root, f"{x1}_{y2}.png")
        mosaic.save(output_path)
        count += 1
        print(f"✅ {x1}_{y2}")

print(f"\n✅ Готово! Создано {count} мозаик 2x2")

# Создаем zip архив
print("\n📦 Создание ZIP архива...")
zip_output = "/content/arcgis_merged_2x2_step2.zip"
with zipfile.ZipFile(zip_output, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files in os.walk(output_root):
        for file in files:
            file_path = os.path.join(root, file)
            arcname = os.path.relpath(file_path, output_root)
            zipf.write(file_path, arcname)

print(f"✅ Архив создан: {zip_output}")

import os
import shutil

# Удаляем папку arcgis_data и все связанные с ней
paths_to_remove = [
    "/content/arcgis_data",
    "/content/arcgis_extracted",
    "/content/arcgis_merged_2x2",
    "/content/arcgis_merged_2x2_no_overlap",
    "/content/arcgis_merged_2x2_step2",
    "/content/arcgis_merged_2x2.zip",
    "/content/arcgis_merged_2x2_no_overlap.zip",
    "/content/arcgis_merged_2x2_step2.zip"
]

for path in paths_to_remove:
    if os.path.exists(path):
        if os.path.isdir(path):
            shutil.rmtree(path)
            print(f"🗑️ Удалена папка: {path}")
        elif os.path.isfile(path):
            os.remove(path)
            print(f"🗑️ Удален файл: {path}")

# Также удаляем все что начинается с arcgis_
for item in os.listdir("/content"):
    item_path = os.path.join("/content", item)
    if item.startswith("arcgis_"):
        if os.path.isdir(item_path):
            shutil.rmtree(item_path)
            print(f"🗑️ Удалена папка: {item}")
        elif os.path.isfile(item_path):
            os.remove(item_path)
            print(f"🗑️ Удален файл: {item}")

print("\n✅ Все arcgis_ данные удалены!")

import os
import zipfile
from PIL import Image
from pathlib import Path
import shutil

# 1. Распаковка arcgis.zip
zip_path = "/content/arcgis.zip"
extract_path = "/content/arcgis_data"

if os.path.exists(zip_path):
    print("📦 Распаковка arcgis.zip...")
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print("✅ Распаковано")
else:
    print("❌ arcgis.zip не найден!")
    exit()

# 2. Поиск папки 18
arcgis_18 = None
for path in Path(extract_path).rglob("18"):
    if path.is_dir():
        arcgis_18 = path
        break

if arcgis_18 is None:
    print("❌ Папка '18' не найдена!")
    exit()

print(f"✅ Найдена папка 18: {arcgis_18}")

# 3. Диапазоны
x_range = list(range(145028, 145081))  # 145028-145080
y_range = list(range(78406, 78451))  # 78451-78407 (сверху вниз)

print(f"X диапазон: {x_range[0]} - {x_range[-1]} (всего {len(x_range)})")
print(f"Y диапазон: {y_range[0]} - {y_range[-1]} (всего {len(y_range)})")

# 4. Создаем корневую папку для результатов
output_root = "/content/merged_results"
os.makedirs(output_root, exist_ok=True)

# 5. Размер одного тайла
first_x = x_range[0]
first_y = y_range[0]
sample_path = arcgis_18 / str(first_x) / f"{first_y}.jpg"
if not sample_path.exists():
    sample_path = arcgis_18 / str(first_x) / f"{first_y}.png"

sample = Image.open(sample_path)
w, h = sample.size
print(f"Размер тайла: {w}x{h}")

# 6. Объединяем с шагом 2
count = 0
for i in range(0, len(x_range) - 1, 2):
    x_left = x_range[i]
    x_right = x_range[i + 1]

    # Создаем папку с координатой X левого нижнего угла
    output_dir = os.path.join(output_root, str(x_left))
    os.makedirs(output_dir, exist_ok=True)

    for j in range(0, len(y_range) - 1, 2):
        y_top = y_range[j]      # верхний ряд
        y_bottom = y_range[j + 1]  # нижний ряд

        # Создаем мозаику 2x2
        mosaic = Image.new('RGB', (w * 2, h * 2))

        # Тайлы: (левый верхний, правый верхний, левый нижний, правый нижний)
        tiles = [
            (x_left, y_top, 0, 0),           # левый верхний
            (x_right, y_top, w, 0),          # правый верхний
            (x_left, y_bottom, 0, h),        # левый нижний
            (x_right, y_bottom, w, h)        # правый нижний
        ]

        for tx, ty, px, py in tiles:
            tile_path = arcgis_18 / str(tx) / f"{ty}.jpg"
            if not tile_path.exists():
                tile_path = arcgis_18 / str(tx) / f"{ty}.png"
            if tile_path.exists():
                tile = Image.open(tile_path)
                mosaic.paste(tile, (px, py))

        # Сохраняем с именем = Y координата левого нижнего угла
        output_path = os.path.join(output_dir, f"{y_bottom}.png")
        mosaic.save(output_path)
        count += 1

        if count % 50 == 0:
            print(f"Прогресс: {count} мозаик")

print(f"\n✅ Создано {count} мозаик 2x2")
print(f"📁 Структура: {output_root}/[X_координата]/[Y_координата].png")
print(f"   Где (X, Y) - координаты левого нижнего угла")

# 7. Создаем ZIP архив
print("\n📦 Создание ZIP архива...")
zip_output = "/content/merged_results.zip"
with zipfile.ZipFile(zip_output, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files in os.walk(output_root):
        for file in files:
            file_path = os.path.join(root, file)
            arcname = os.path.relpath(file_path, output_root)
            zipf.write(file_path, arcname)

print(f"✅ Архив создан: {zip_output}")
print(f"📦 Размер: {os.path.getsize(zip_output) / (1024*1024):.2f} MB")

import os
print("Содержимое /content:")
for item in os.listdir("/content"):
    if "merged" in item:
        print(f"  📁 {item}")

import os
from PIL import Image
from pathlib import Path

def build_2x2_mosaic(arcgis_18_path, x_idx, y_idx):
    """
    Собирает мозаику 2x2 из тайлов по схеме:
    (x_idx, y_idx)     (x_idx, y_idx+1)
    (x_idx-1, y_idx)   (x_idx-1, y_idx+1)

    arcgis_18_path: путь к папке 18 (Path object)
    x_idx: индекс X (номер папки)
    y_idx: индекс Y (номер файла)
    """
    # Получаем списки X и Y
    all_x = sorted([int(f.name) for f in arcgis_18_path.iterdir()
                    if f.is_dir() and f.name.isdigit()])

    first_folder = arcgis_18_path / str(all_x[0])
    all_y = sorted([int(f.stem) for f in first_folder.glob("*")
                    if f.suffix in ['.jpg', '.png', '.jpeg']], reverse=True)

    # Находим координаты по индексам
    x_right = all_x[x_idx]      # n
    x_left = all_x[x_idx - 1]   # n-1
    y_top = all_y[y_idx]        # m
    y_bottom = all_y[y_idx + 1] # m+1

    print(f"Тайлы:")
    print(f"  Левый верхний:     X={x_left}, Y={y_top}")
    print(f"  Правый верхний:    X={x_right}, Y={y_top}")
    print(f"  Левый нижний:      X={x_left}, Y={y_bottom}")
    print(f"  Правый нижний:     X={x_right}, Y={y_bottom}")

    # Загружаем размер
    sample_path = arcgis_18_path / str(x_left) / f"{y_top}.jpg"
    if not sample_path.exists():
        sample_path = arcgis_18_path / str(x_left) / f"{y_top}.png"
    sample = Image.open(sample_path)
    w, h = sample.size

    # Создаем мозаику
    mosaic = Image.new('RGB', (w * 2, h * 2))

    # Левый верхний
    tile_path = arcgis_18_path / str(x_left) / f"{y_top}.jpg"
    if not tile_path.exists():
        tile_path = arcgis_18_path / str(x_left) / f"{y_top}.png"
    mosaic.paste(Image.open(tile_path), (0, 0))

    # Правый верхний
    tile_path = arcgis_18_path / str(x_right) / f"{y_top}.jpg"
    if not tile_path.exists():
        tile_path = arcgis_18_path / str(x_right) / f"{y_top}.png"
    mosaic.paste(Image.open(tile_path), (w, 0))

    # Левый нижний
    tile_path = arcgis_18_path / str(x_left) / f"{y_bottom}.jpg"
    if not tile_path.exists():
        tile_path = arcgis_18_path / str(x_left) / f"{y_bottom}.png"
    mosaic.paste(Image.open(tile_path), (0, h))

    # Правый нижний
    tile_path = arcgis_18_path / str(x_right) / f"{y_bottom}.jpg"
    if not tile_path.exists():
        tile_path = arcgis_18_path / str(x_right) / f"{y_bottom}.png"
    mosaic.paste(Image.open(tile_path), (w, h))

    # Сохраняем
    output_dir = f"/content/mosaic_{x_left}_{y_bottom}"
    os.makedirs(output_dir, exist_ok=True)
    output_path = f"{output_dir}/mosaic.png"
    mosaic.save(output_path)
    print(f"✅ Сохранено: {output_path}")
    return mosaic

# Путь к папке 18
arcgis_18 = None
for path in Path("/content").rglob("18"):
    if path.is_dir():
        arcgis_18 = path
        break

if arcgis_18:
    print(f"Найдена папка: {arcgis_18}")
    # Собрать мозаику с X индексом 5, Y индексом 3
    build_2x2_mosaic(arcgis_18, x_idx=5, y_idx=3)
else:
    print("Папка 18 не найдена")

import os
from PIL import Image
from pathlib import Path
import zipfile
from google.colab import files
from datetime import datetime

# 1. РАСПАКОВКА ZIP АРХИВА arcgis.zip
zip_path = "/content/arcgis.zip"
extract_dir = "/content/arcgis_data"

if os.path.exists(zip_path):
    print("📦 Распаковка arcgis.zip...")
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_dir)
    print("✅ Распаковано")
else:
    print("❌ Файл arcgis.zip не найден!")
    exit()

# 2. Ищем папку arcgis/18
arcgis_18 = None
for path in Path(extract_dir).rglob("18"):
    if path.is_dir() and "arcgis" in str(path):
        arcgis_18 = path
        break

if arcgis_18 is None:
    print("❌ Папка 'arcgis/18' не найдена!")
    exit()

print(f"✅ Найдена папка: {arcgis_18}")

def merge_original_tiles_with_step(base_dir, N, M, step, x_range, y_range):
    """
    Объединяет оригинальные тайлы из arcgis в мозаики N x M с шагом step
    """
    # Получаем все X папки (числовые папки внутри 18)
    all_x = sorted([int(f.name) for f in Path(base_dir).iterdir() if f.is_dir() and f.name.isdigit()])

    # Фильтруем по диапазону
    all_x = [x for x in all_x if x_range[0] <= x <= x_range[1]]

    if len(all_x) == 0:
        print(f"❌ Нет X папок в диапазоне {x_range}")
        print(f"Доступные X: {all_x[:20]}...")
        return

    # Получаем все Y файлы из первой папки
    first_folder = Path(base_dir) / str(all_x[0])
    all_y = sorted([int(f.stem) for f in first_folder.glob("*") if f.suffix in ['.jpg', '.png', '.jpeg']])
    all_y = [y for y in all_y if y_range[0] <= y <= y_range[1]]
    all_y = sorted(all_y)  # Y возрастает сверху вниз

    if len(all_y) == 0:
        print(f"❌ Нет Y файлов в диапазоне {y_range}")
        print(f"Доступные Y: {all_y[:20]}...")
        return

    print(f"Найдено X папок: {len(all_x)} (от {all_x[0]} до {all_x[-1]})")
    print(f"Найдено Y файлов: {len(all_y)} (от {all_y[0]} до {all_y[-1]})")

    # Загружаем размер тайла
    sample_path = first_folder / f"{all_y[0]}.jpg"
    if not sample_path.exists():
        sample_path = first_folder / f"{all_y[0]}.png"
    sample = Image.open(sample_path)
    w, h = sample.size
    print(f"Размер тайла: {w}x{h}")

    # Создаем папку для результатов
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_root = f"/content/arcgis_merged_{timestamp}"
    os.makedirs(output_root, exist_ok=True)
    print(f"\n📁 Результаты сохраняются в: {output_root}")

    # Подсчет общего количества
    total_x = len(range(0, len(all_x) - N + 1, step))
    total_y = len(range(0, len(all_y) - M + 1, step))
    total_count = total_x * total_y

    print(f"📊 Всего будет создано мозаик: {total_count}\n")

    count = 0
    # Проходим с шагом step
    for start_x_idx in range(0, len(all_x) - N + 1, step):
        for start_y_idx in range(0, len(all_y) - M + 1, step):
            # Координаты левого нижнего угла
            bottom_left_x = all_x[start_x_idx]
            bottom_left_y = all_y[start_y_idx + M - 1]

            # Создаем мозаику
            mosaic = Image.new('RGB', (w * N, h * M))

            for i in range(N):
                x = all_x[start_x_idx + i]
                x_folder = Path(base_dir) / str(x)
                for j in range(M):
                    y = all_y[start_y_idx + j]
                    tile_path = x_folder / f"{y}.jpg"
                    if not tile_path.exists():
                        tile_path = x_folder / f"{y}.png"
                    if tile_path.exists():
                        tile = Image.open(tile_path)
                        mosaic.paste(tile, (i * w, j * h))

            # Сохраняем с именем по левому нижнему углу
            output_filename = f"{bottom_left_x}_{bottom_left_y}.png"
            output_path = os.path.join(output_root, output_filename)
            mosaic.save(output_path)
            count += 1

            if count % 10 == 0:
                print(f"✅ Создано {count}/{total_count} | Левый нижний: ({bottom_left_x},{bottom_left_y})")

    print(f"\n{'='*50}")
    print(f"🎉 ГОТОВО! Всего создано мозаик: {count}")
    print(f"📁 Папка: {output_root}")
    print(f"{'='*50}\n")

    if count > 0:
        # Создаем ZIP архив
        print("📦 Создание ZIP архива...")
        zip_output = f"/content/arcgis_merged_{timestamp}.zip"
        with zipfile.ZipFile(zip_output, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for root, dirs, files_list in os.walk(output_root):
                for file in files_list:
                    file_path = os.path.join(root, file)
                    arcname = os.path.relpath(file_path, output_root)
                    zipf.write(file_path, arcname)

        file_size = os.path.getsize(zip_output) / (1024*1024)
        print(f"✅ Архив создан: {zip_output}")
        print(f"📦 Размер: {file_size:.2f} MB")

        # Скачиваем
        print("\n📥 Скачивание...")
        files.download(zip_output)
    else:
        print("❌ Не создано ни одной мозаики!")

# Параметры
base_dir = str(arcgis_18)
N =   # ширина в тайлах
M = 10  # высота в тайлах
step = 5  # шаг
x_range = (145028, 145080)
y_range = (78407, 78451)

# Запуск
merge_original_tiles_with_step(base_dir, N, M, step, x_range, y_range)

import os
from PIL import Image
from pathlib import Path
import zipfile
from google.colab import files
from datetime import datetime

# 1. РАСПАКОВКА ZIP АРХИВА arcgis.zip
zip_path = "/content/arcgis.zip"
extract_dir = "/content/arcgis_data"

if os.path.exists(zip_path):
    print("📦 Распаковка arcgis.zip...")
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_dir)
    print("✅ Распаковано")
else:
    print("❌ Файл arcgis.zip не найден!")
    exit()

# 2. Ищем папку arcgis/18
arcgis_18 = None
for path in Path(extract_dir).rglob("18"):
    if path.is_dir() and "arcgis" in str(path):
        arcgis_18 = path
        break

if arcgis_18 is None:
    print("❌ Папка 'arcgis/18' не найдена!")
    exit()

print(f"✅ Найдена папка: {arcgis_18}")

def merge_original_tiles_with_step(base_dir, N, M, step, x_range, y_range):
    """
    Объединяет оригинальные тайлы из arcgis в мозаики N x M с шагом step
    """
    # Получаем все X папки (числовые папки внутри 18)
    all_x = sorted([int(f.name) for f in Path(base_dir).iterdir() if f.is_dir() and f.name.isdigit()])

    # Фильтруем по диапазону
    all_x = [x for x in all_x if x_range[0] <= x <= x_range[1]]

    if len(all_x) == 0:
        print(f"❌ Нет X папок в диапазоне {x_range}")
        print(f"Доступные X: {all_x[:20]}...")
        return

    # Получаем все Y файлы из первой папки
    first_folder = Path(base_dir) / str(all_x[0])
    all_y = sorted([int(f.stem) for f in first_folder.glob("*") if f.suffix in ['.jpg', '.png', '.jpeg']])
    all_y = [y for y in all_y if y_range[0] <= y <= y_range[1]]
    all_y = sorted(all_y)  # Y возрастает сверху вниз

    if len(all_y) == 0:
        print(f"❌ Нет Y файлов в диапазоне {y_range}")
        print(f"Доступные Y: {all_y[:20]}...")
        return

    print(f"Найдено X папок: {len(all_x)} (от {all_x[0]} до {all_x[-1]})")
    print(f"Найдено Y файлов: {len(all_y)} (от {all_y[0]} до {all_y[-1]})")

    # Загружаем размер тайла
    sample_path = first_folder / f"{all_y[0]}.jpg"
    if not sample_path.exists():
        sample_path = first_folder / f"{all_y[0]}.png"
    sample = Image.open(sample_path)
    w, h = sample.size
    print(f"Размер тайла: {w}x{h}")

    # Создаем папку для результатов
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_root = f"/content/best_win_team_gg_{timestamp}"
    os.makedirs(output_root, exist_ok=True)
    print(f"\n📁 Результаты сохраняются в: {output_root}")

    # Подсчет общего количества
    total_x = len(range(0, len(all_x) - N + 1, step))
    total_y = len(range(0, len(all_y) - M + 1, step))
    total_count = total_x * total_y

    print(f"📊 Всего будет создано мозаик: {total_count}\n")

    count = 0
    # Проходим с шагом step
    for start_x_idx in range(0, len(all_x) - N + 1, step):
        for start_y_idx in range(0, len(all_y) - M + 1, step):
            # Координаты левого нижнего угла
            bottom_left_x = all_x[start_x_idx]
            bottom_left_y = all_y[start_y_idx + M - 1]

            # Создаем мозаику
            mosaic = Image.new('RGB', (w * N, h * M))

            for i in range(N):
                x = all_x[start_x_idx + i]
                x_folder = Path(base_dir) / str(x)
                for j in range(M):
                    y = all_y[start_y_idx + j]
                    tile_path = x_folder / f"{y}.jpg"
                    if not tile_path.exists():
                        tile_path = x_folder / f"{y}.png"
                    if tile_path.exists():
                        tile = Image.open(tile_path)
                        mosaic.paste(tile, (i * w, j * h))

            # Сохраняем с именем по левому нижнему углу
            output_filename = f"{bottom_left_x}_{bottom_left_y}.png"
            output_path = os.path.join(output_root, output_filename)
            mosaic.save(output_path)
            count += 1

            if count % 10 == 0:
                print(f"✅ Создано {count}/{total_count} | Левый нижний: ({bottom_left_x},{bottom_left_y})")

    print(f"\n{'='*50}")
    print(f"🎉 ГОТОВО! Всего создано мозаик: {count}")
    print(f"📁 Папка: {output_root}")
    print(f"{'='*50}\n")

    if count > 0:
        # Создаем ZIP архив
        print("📦 Создание ZIP архива...")
        zip_output = f"/content/best_win_team_gg_{timestamp}.zip"
        with zipfile.ZipFile(zip_output, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for root, dirs, files_list in os.walk(output_root):
                for file in files_list:
                    file_path = os.path.join(root, file)
                    arcname = os.path.relpath(file_path, output_root)
                    zipf.write(file_path, arcname)

        file_size = os.path.getsize(zip_output) / (1024*1024)
        print(f"✅ Архив создан: {zip_output}")
        print(f"📦 Размер: {file_size:.2f} MB")

        # Скачиваем
        print("\n📥 Скачивание...")
        files.download(zip_output)
    else:
        print("❌ Не создано ни одной мозаики!")

# Параметры
base_dir = str(arcgis_18)
N = 4  # ширина в тайлах
M = 4  # высота в тайлах
step = 2  # шаг
x_range = (145028, 145080)
y_range = (78407, 78451)

# Запуск
merge_original_tiles_with_step(base_dir, N, M, step, x_range, y_range)

import os
from PIL import Image
from pathlib import Path
import zipfile
import torch
import numpy as np
from transformers import AutoImageProcessor, Mask2FormerForUniversalSegmentation
from datetime import datetime
from google.colab import files

# 1. РАСПАКОВКА МОДЕЛИ
print("📦 Распаковка модели mask2former_finetuned_new.zip...")
with zipfile.ZipFile("/content/mask2former_finetuned_new.zip", 'r') as zip_ref:
    zip_ref.extractall("/content/mask2former_model")
print("✅ Модель распакована")

# 2. ПОИСК ПАПКИ С МОДЕЛЬЮ
model_path = None
for root, dirs, files in os.walk("/content/mask2former_model"):
    if "config.json" in files:
        has_weights = ("pytorch_model.bin" in files or "model.safetensors" in files)
        if has_weights:
            model_path = root
            break

if model_path is None:
    print("❌ Модель не найдена!")
    exit()

print(f"✅ Модель найдена: {model_path}")

# 3. ЗАГРУЗКА МОДЕЛИ
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"🔧 Устройство: {device}")

processor = AutoImageProcessor.from_pretrained(model_path, local_files_only=True)
model = Mask2FormerForUniversalSegmentation.from_pretrained(model_path, local_files_only=True)
model.to(device)
model.eval()
print("✅ Модель загружена")

# 4. ЦВЕТА ДЛЯ СЕГМЕНТАЦИИ
colors = np.array([
    [0, 0, 0], [0, 255, 0], [255, 255, 0], [0, 0, 255],
    [255, 0, 0], [128, 128, 128], [255, 0, 255], [255, 165, 0],
])

def segment_image(image_path):
    """Сегментирует одно изображение"""
    image = Image.open(image_path).convert("RGB")
    original_size = image.size[::-1]

    inputs = processor(images=image, return_tensors="pt")
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)

    pred_mask = processor.post_process_semantic_segmentation(outputs, target_sizes=[original_size])[0]
    pred_mask_np = pred_mask.cpu().numpy()

    h, w = pred_mask_np.shape
    rgb_mask = np.zeros((h, w, 3), dtype=np.uint8)
    for class_id, color in enumerate(colors):
        if class_id < len(colors):
            rgb_mask[pred_mask_np == class_id] = color

    return rgb_mask

# 5. СОЗДАЕМ ПАПКУ ДЛЯ РЕЗУЛЬТАТОВ СРАЗУ
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
output_root = f"/content/segmented_slave_{timestamp}"
os.makedirs(output_root, exist_ok=True)
print(f"\n📁 Папка для результатов создана: {output_root}")

# 6. ПОИСК ВСЕХ ПАПОК best_win_team_gg
print("\n🔍 Поиск папок best_win_team_gg...")
input_folders = []
for path in Path("/content").glob("best_win_team_gg_*"):
    if path.is_dir():
        input_folders.append(path)
        print(f"  Найдено: {path.name}")

if len(input_folders) == 0:
    print("❌ Папки best_win_team_gg не найдены!")
    exit()

# 7. СЕГМЕНТАЦИЯ ДЛЯ КАЖДОЙ ПАПКИ
for input_folder in input_folders:
    print(f"\n{'='*60}")
    print(f"📁 Обработка: {input_folder.name}")
    print(f"{'='*60}")

    # Создаем подпапку в output_root
    folder_output = os.path.join(output_root, input_folder.name)
    os.makedirs(folder_output, exist_ok=True)

    # Находим все PNG файлы в папке
    image_files = sorted([f for f in input_folder.glob("*.png")])

    if len(image_files) == 0:
        print(f"⚠️ Нет PNG файлов в {input_folder.name}")
        continue

    print(f"📷 Найдено изображений: {len(image_files)}")

    # Сегментируем каждый файл
    count = 0
    for img_path in image_files:
        try:
            # Сегментируем
            segmented = segment_image(str(img_path))

            # Сохраняем с тем же именем
            output_path = os.path.join(folder_output, img_path.name)
            Image.fromarray(segmented).save(output_path)
            count += 1

            if count % 10 == 0:
                print(f"  ✅ Сегментировано: {count}/{len(image_files)}")
        except Exception as e:
            print(f"  ❌ Ошибка {img_path.name}: {e}")

    print(f"✅ Завершено! Сохранено {count} файлов в {folder_output}")

print(f"\n{'='*60}")
print(f"🎉 ВСЕ ЗАВЕРШЕНО!")
print(f"📁 Все результаты в папке: {output_root}")
print(f"{'='*60}")

# 8. СОЗДАЕМ ОБЩИЙ ZIP АРХИВ
print("\n📦 Создание общего ZIP архива...")
zip_output = f"/content/segmented_slave_{timestamp}.zip"
with zipfile.ZipFile(zip_output, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files_list in os.walk(output_root):
        for file in files_list:
            file_path = os.path.join(root, file)
            arcname = os.path.relpath(file_path, output_root)
            zipf.write(file_path, arcname)

file_size = os.path.getsize(zip_output) / (1024*1024)
print(f"✅ Архив создан: {zip_output}")
print(f"📦 Размер: {file_size:.2f} MB")

# 9. СКАЧИВАЕМ
print("\n📥 Скачивание...")
files.download(zip_output)

from google.colab import files
import os
import zipfile
from datetime import datetime

# Путь к папке
folder_path = "/content/segmented_slave_20260423_023909/best_win_team_gg_20260423_022515"

if os.path.exists(folder_path):
    # Создаем ZIP архив
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    zip_name = f"best_win_team_gg_{timestamp}.zip"
    zip_path = f"/content/{zip_name}"

    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(folder_path):
            for file in files:
                file_path = os.path.join(root, file)
                arcname = os.path.relpath(file_path, folder_path)
                zipf.write(file_path, arcname)

    print(f"✅ Архив создан: {zip_path}")
    print(f"📦 Размер: {os.path.getsize(zip_path) / (1024*1024):.2f} MB")

    # Скачиваем
    files.download(zip_path)
else:
    print("❌ Папка не найдена!")

from google.colab import files
import os
import zipfile
from datetime import datetime

# Путь к папке
folder_path = "/content/segmented_slave_20260423_023909/best_win_team_gg_20260423_022515"

if os.path.exists(folder_path):
    # Создаем ZIP архив
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    zip_name = f"best_win_team_gg_{timestamp}.zip"
    zip_path = f"/content/{zip_name}"

    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files_list in os.walk(folder_path):
            for file in files_list:
                file_path = os.path.join(root, file)
                arcname = os.path.relpath(file_path, folder_path)
                zipf.write(file_path, arcname)

    print(f"✅ Архив создан: {zip_path}")
    print(f"📦 Размер: {os.path.getsize(zip_path) / (1024*1024):.2f} MB")

    # Скачиваем
    files.download(zip_path)
else:
    print("❌ Папка не найдена!")

import os
from PIL import Image
from pathlib import Path
import random
import matplotlib.pyplot as plt

def show_3x3_mosaic_center(folder_path):
    """
    Собирает мозаику 3x3 вокруг центральной точки с шагом 4
    Сетка:
    (x-4, y-4)  (x, y-4)  (x+4, y-4)
    (x-4, y)    (x, y)    (x+4, y)
    (x-4, y+4)  (x, y+4)  (x+4, y+4)
    """
    # Получаем все PNG файлы
    image_files = [f for f in Path(folder_path).glob("*.png")]

    if len(image_files) == 0:
        print("❌ Нет изображений в папке!")
        return

    # Создаем словарь для быстрого доступа
    tile_dict = {}
    for f in image_files:
        x, y = map(int, f.stem.split('_'))
        tile_dict[(x, y)] = f

    # Получаем все доступные координаты
    all_x = sorted(set(x for x, _ in tile_dict.keys()))
    all_y = sorted(set(y for _, y in tile_dict.keys()))

    # Выбираем случайную центральную точку (не слишком близко к краям)
    min_x = min(all_x) + 4
    max_x = max(all_x) - 4
    min_y = min(all_y) + 4
    max_y = max(all_y) - 4

    if min_x > max_x or min_y > max_y:
        print("❌ Недостаточно места для шага 4!")
        return

    center_x = random.choice([x for x in all_x if min_x <= x <= max_x])
    center_y = random.choice([y for y in all_y if min_y <= y <= max_y])

    # Координаты сетки 3x3
    offsets = [-4, 0, 4]
    grid = []
    for dy in offsets:
        for dx in offsets:
            x = center_x + dx
            y = center_y + dy
            grid.append((x, y))

    print(f"\n📊 Центр: X={center_x}, Y={center_y}")
    print(f"📊 Координаты:")
    for x, y in grid:
        print(f"    X={x}, Y={y} -> {'✅' if (x,y) in tile_dict else '❌'}")

    # Проверяем что все 9 картинок есть
    missing = [c for c in grid if c not in tile_dict]
    if missing:
        print(f"\n❌ Отсутствуют картинки: {missing}")
        return

    # Загружаем размер
    sample = Image.open(tile_dict[grid[0]])
    w, h = sample.size

    # Создаем мозаику
    mosaic = Image.new('RGB', (w * 3, h * 3))

    for idx, (x, y) in enumerate(grid):
        row = idx // 3
        col = idx % 3
        img = Image.open(tile_dict[(x, y)])
        mosaic.paste(img, (col * w, row * h))

    # Показываем
    plt.figure(figsize=(12, 12))
    plt.imshow(mosaic)
    plt.title(f"Мозаика 3x3 с шагом 4\nЦентр: ({center_x}, {center_y})", fontsize=12)
    plt.axis('off')
    plt.show()

# Использование
folder_path = "/content/segmented_slave_20260423_023909/best_win_team_gg_20260423_022515"
show_3x3_mosaic_center(folder_path)

import os
from PIL import Image
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np

def build_map_with_stride_4(folder_path, show_preview=True, save_path=None):
    """
    Собирает карту с шагом 4 (пропуская каждый второй тайл по X и Y)
    Так как файлы лежат с шагом 2, берем каждый второй файл = шаг 4
    """

    # Получаем все PNG файлы
    image_files = list(Path(folder_path).glob("*.png"))

    if len(image_files) == 0:
        print("❌ Нет изображений в папке!")
        return None

    print(f"📁 Найдено тайлов: {len(image_files)}")

    # Парсим координаты из имен файлов
    tile_dict = {}
    for f in image_files:
        try:
            x, y = map(int, f.stem.split('_'))
            tile_dict[(x, y)] = f
        except:
            print(f"⚠️ Пропущен файл с нестандартным именем: {f.name}")

    # Получаем все уникальные координаты
    all_x = sorted(set(x for x, _ in tile_dict.keys()))
    all_y = sorted(set(y for _, y in tile_dict.keys()))

    print(f"\n📊 Исходные данные:")
    print(f"  Диапазон X: {min(all_x)} → {max(all_x)} (всего {len(all_x)} значений)")
    print(f"  Диапазон Y: {min(all_y)} → {max(all_y)} (всего {len(all_y)} значений)")

    # Проверяем шаг между соседними координатами
    if len(all_x) > 1:
        x_step = all_x[1] - all_x[0]
        print(f"  Шаг по X в файлах: {x_step}")
    if len(all_y) > 1:
        y_step = all_y[1] - all_y[0]
        print(f"  Шаг по Y в файлах: {y_step}")

    # Берем каждый второй элемент (шаг 4 вместо 2)
    selected_x = all_x[::2]  # [0, 2, 4, 6, ...] -> каждый второй
    selected_y = all_y[::2]  # [0, 2, 4, 6, ...] -> каждый второй

    print(f"\n📊 После прореживания (шаг 4):")
    print(f"  Выбрано X: {len(selected_x)} из {len(all_x)}")
    print(f"  Выбрано Y: {len(selected_y)} из {len(all_y)}")
    print(f"  Диапазон выбранных X: {min(selected_x)} → {max(selected_x)}")
    print(f"  Диапазон выбранных Y: {min(selected_y)} → {max(selected_y)}")

    # Проверяем наличие всех нужных тайлов
    missing_tiles = []
    for x in selected_x:
        for y in selected_y:
            if (x, y) not in tile_dict:
                missing_tiles.append((x, y))

    if missing_tiles:
        print(f"\n⚠️ Отсутствует {len(missing_tiles)} тайлов из выбранных")
        if len(missing_tiles) <= 20:
            print("Отсутствующие координаты:", missing_tiles)

    # Загружаем размер одного тайла
    first_x, first_y = selected_x[0], selected_y[0]
    sample_tile = Image.open(tile_dict[(first_x, first_y)])
    tile_w, tile_h = sample_tile.size
    print(f"\n📐 Размер одного тайла: {tile_w}x{tile_h}")

    # Размеры полной карты
    cols = len(selected_x)
    rows = len(selected_y)
    full_w = tile_w * cols
    full_h = tile_h * rows

    print(f"🗺️ Размер итоговой карты: {full_w}x{full_h} пикселей ({cols}x{rows} тайлов)")

    # Проверяем память
    memory_mb = (full_w * full_h * 3) / (1024 * 1024)
    print(f"💾 Примерный размер в памяти: {memory_mb:.1f} МБ")

    # Создаем пустую карту
    print("\n🔨 Собираю карту с шагом 4...")
    full_map = Image.new('RGB', (full_w, full_h))

    # Заполняем карту выбранными тайлами
    for row_idx, y in enumerate(selected_y):
        for col_idx, x in enumerate(selected_x):
            if (x, y) in tile_dict:
                tile = Image.open(tile_dict[(x, y)])
                full_map.paste(tile, (col_idx * tile_w, row_idx * tile_h))
            else:
                # Заполняем черным отсутствующие тайлы
                black_tile = Image.new('RGB', (tile_w, tile_h), color='black')
                full_map.paste(black_tile, (col_idx * tile_w, row_idx * tile_h))

        # Прогресс
        if (row_idx + 1) % 10 == 0:
            print(f"  Прогресс: {row_idx + 1}/{rows} строк обработано")

    print("✅ Карта собрана!")

    # Сохраняем если нужно
    if save_path:
        print(f"\n💾 Сохраняю карту в {save_path}...")
        full_map.save(save_path)
        print("✅ Сохранено!")

    # Показываем превью
    if show_preview:
        max_display_size = 2000
        if full_w > max_display_size or full_h > max_display_size:
            scale = max_display_size / max(full_w, full_h)
            preview_w = int(full_w * scale)
            preview_h = int(full_h * scale)
            preview_map = full_map.resize((preview_w, preview_h), Image.Resampling.LANCZOS)
            print(f"\n👁️ Показываю превью (уменьшено до {preview_w}x{preview_h})...")
        else:
            preview_map = full_map
            print(f"\n👁️ Показываю полную карту...")

        plt.figure(figsize=(15, 15))
        plt.imshow(preview_map)
        plt.title(f"Карта с шагом 4\nРазмер: {full_w}x{full_h} | Тайлов: {cols}x{rows}", fontsize=14)
        plt.axis('off')
        plt.tight_layout()
        plt.show()

    return full_map

def show_selection_pattern(folder_path):
    """
    Визуализирует, какие тайлы выбраны (шаг 4) а какие пропущены
    """
    image_files = list(Path(folder_path).glob("*.png"))

    # Парсим координаты
    tile_dict = {}
    for f in image_files:
        try:
            x, y = map(int, f.stem.split('_'))
            tile_dict[(x, y)] = f
        except:
            pass

    all_x = sorted(set(x for x, _ in tile_dict.keys()))
    all_y = sorted(set(y for _, y in tile_dict.keys()))

    # Создаем матрицу: 2 = выбран (каждый второй), 1 = есть но пропущен, 0 = отсутствует
    grid = np.zeros((len(all_y), len(all_x)))

    for row_idx, y in enumerate(all_y):
        for col_idx, x in enumerate(all_x):
            if (x, y) in tile_dict:
                # Проверяем, выбран ли этот тайл (каждый второй по обеим осям)
                x_selected = (all_x.index(x) % 2 == 0)
                y_selected = (all_y.index(y) % 2 == 0)

                if x_selected and y_selected:
                    grid[row_idx, col_idx] = 2  # Выбран
                else:
                    grid[row_idx, col_idx] = 1  # Есть, но пропущен

    # Визуализация
    plt.figure(figsize=(12, 10))

    # Создаем цветовую карту
    from matplotlib.colors import ListedColormap
    cmap = ListedColormap(['black', 'orange', 'green'])

    plt.imshow(grid, cmap=cmap, interpolation='nearest')
    plt.title("Схема выбора тайлов (шаг 4)\n🟢 Выбраны | 🟠 Пропущены | ⚫ Отсутствуют",
              fontsize=14, pad=20)
    plt.xlabel("Индекс X")
    plt.ylabel("Индекс Y")

    # Легенда
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='green', label='Выбраны (каждый 2-й по X и Y)'),
        Patch(facecolor='orange', label='Пропущены (есть в данных)'),
        Patch(facecolor='black', label='Отсутствуют в данных')
    ]
    plt.legend(handles=legend_elements, loc='upper right', bbox_to_anchor=(1.15, 1))

    # Статистика
    selected = np.sum(grid == 2)
    skipped = np.sum(grid == 1)
    missing = np.sum(grid == 0)

    print(f"\n📊 Статистика выборки:")
    print(f"  🟢 Выбрано: {selected} тайлов")
    print(f"  🟠 Пропущено: {skipped} тайлов")
    print(f"  ⚫ Отсутствует: {missing} тайлов")
    print(f"  📦 Всего в данных: {selected + skipped} тайлов")

    plt.tight_layout()
    plt.show()

    return grid

# ============================================================
# ИСПОЛЬЗОВАНИЕ
# ============================================================

folder_path = "/content/segmented_slave_20260423_023909/best_win_team_gg_20260423_022515"

# Сначала показываем схему выборки
print("="*60)
print("СХЕМА ВЫБОРКИ ТАЙЛОВ (ШАГ 4)")
print("="*60)
selection_grid = show_selection_pattern(folder_path)

print("\n" + "="*60)
print("СБОРКА КАРТЫ С ШАГОМ 4")
print("="*60)

# Собираем карту с шагом 4
full_map = build_map_with_stride_4(
    folder_path,
    show_preview=True,
    save_path="full_map_stride_4.png"
)

print("\n✅ Готово!")
print("Карта собрана с шагом 4 (каждый второй тайл по X и Y пропущен)")
